from agents import ChagAgent 
from states import AgentState
from dotenv import load_dotenv
import os
import json
from langchain_groq import ChatGroq

load_dotenv()
groq_api = os.getenv("GROQ_API_KEY")

LLM  = ChatGroq(api_key=groq_api,model="llama-3.1-70b-versatile")


def test_chat_agent(query: str):
    agent = ChagAgent(_llm = LLM)
    
    # Prepare an initial agent state with an example query
    state: AgentState = {
        "user_query": [query],
        "tool_to_use": ["search_vector_store"],  # Let's assume the tool to use is "search_web" for this test
        "vector_results": ["Not able to retrieve documents"],
        "web_results": [],
        "arxiv_results": [],
        "llm_response": ["The researchers in the 'Attention is all you need' paper used 6 encoder layers and 6 decoder layers in their actual application."],
    }
    
    print("Running test with query:", query)

    # Test the flow for processing the query through the agent's graph
    state = agent.Chat_bot(state, query)
    
    # Output the final response after all the tool processing and routing
    print("Final State after processing:")
    print(json.dumps(state, indent=4))

    # Assuming `state["llm_response"]` contains the final response after all tool processing
    final_response = state.get("llm_response", "No response generated")
    print("Final Response Generated by the Agent:")
    print(final_response)

if __name__ =="__main__":
    user_query ="how many encoder decoder were used inside the acutal application by the researcher's in the 'Attention is all you need' paper"
    test_chat_agent(user_query)

